deployment:
  tasks:
    - export DEPLOYPATH=/home/ptiunsulbarac/public_html/
    - /bin/cp -R /home/ptiunsulbarac/repositories/webptiunsulbar/* $DEPLOYPATH
    - /bin/cp -R /home/ptiunsulbarac/repositories/webptiunsulbar/.[!.]* $DEPLOYPATH
