---
deployment:
  tasks:
    - /usr/local/bin/composer install --no-dev --optimize-autoloader
    - /usr/bin/php artisan migrate --force
    - /usr/bin/php artisan config:cache
    - /usr/bin/php artisan route:cache
    - /usr/bin/php artisan view:cache
